backend:
  name: git-gateway
  repo: cpachomski/levoyage

  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload {{collection}} "{{slug}}"'
    deleteMedia: '[skip ci] Upload {{collection}} "{{slug}}"'

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: image, widget: image, required: false }
          - {
              label: "Hero Video Url",
              name: videoUrl,
              widget: string,
              required: false,
            }
          - {
              label: Subheading,
              name: subheading,
              widget: string,
              required: false,
            }
          - {
              label: Description,
              name: description,
              widget: string,
              required: false,
            }
          - label: "Crew Members"
            name: crewMembers
            widget: list
            required: false
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Role, name: role, widget: string }
              - { label: Website Url, name: website, widget: string }
